log:
  path: /Users/${user.name}/data/logs/java/${spring.application.name}

server:
  error:
    include-message: always
  tomcat:
    accesslog:
      enabled: true
      directory: ${log.path}
      prefix: qujia_demo
      suffix: _access.log
      rename-on-rotate: true
      buffered: true

sentinel:
  zookeeper:
    address: 127.0.0.1:2181
    path: /sentinel_rule_config

logging:
  level:
    root: info